name = "my-app"
compatibility_date = "2024-07-12"

[vars]
ENV="development"
DATACENTERS = [
	{ "name" = "aws-us-west-2", "url" = "https://usfss.company.com" },
	{ "name" = "gcp-us-west1", "url" = "https://gfss.compay.com" },
]

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"